name: Build and deploy Node.js app to Azure Web App - sacma-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for requesting the JWT

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_940ABABCAEB8498F9326E8F52A796E25 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9FA3BBE473DF460BAEB8B51F3048A55E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5169EDF95CB7408E80457F065305AE07 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sacma-dev'
          package: .

      - name: Cleanup
        if: always()
        run: rm release.zip